export const GET_CURRENT_NEWS = 'GET_CURRENT_NEWS';

export const GET_TOP_COINS = 'GET_TOP_COINS';
export const GET_COIN_DETAIL = 'GET_COIN_DETAIL';
export const GET_COIN_CURR_SUMMARY = 'GET_COIN_CURR_SUMMARY';
export const CLEAR_COIN_SUMMARY = 'CLEAR_COIN_SUMMARY';
export const CLEAR_COIN_DETAIL = 'CLEAR_COIN_DETAIL';
export const GET_COIN_LIST = 'GET_COIN_LIST';
export const GET_GLOBAL_MARKET_DATA = 'GET_GLOBAL_MARKET_DATA';
export const GET_ACTIVE_PAGE = 'GET_ACTIVE_PAGE';
export const GET_MARKET_VALUE = 'GET_MARKET_VALUE';

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const ADD_TRANSACTIONS = 'ADD_TRANSACTIONS';
export const REMOVE_TRANSACTIONS = 'REMOVE_TRANSACTIONS';
export const FAILED_TRANSACTION = 'FAILED_TRANSACTION';
export const CLEAR_TRANSACTION = 'CLEAR_TRANSACTION';
export const CLEAR_TRANSACTION_ERROR = 'CLEAR_TRANSACTION_ERROR';
